carRentalWeb/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/', include('employee.urls')),
    path('user/', include('user.urls')),
    path('', include('home.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, re_path
from . import views

app_name = 'home'

urlpatterns = [
    path("", views.index, name="index"),
    path("cars/", views.available_cars, name="cars"),
    path("client_rentals/", views.client_rentals, name='client_rentals'),
    path("car_details/<int:car_id>/", views.car_details, name='car_details'),
    path('rent_car/<int:car_id>/', views.rent_car, name='rent_car'),

]

user/urls.py
from django.urls import path
from .views import update_view, login_view, logout_view, register_view

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name="register"),
    path('profil/', update_view, name="profil"),
]

employee/models.py
from django.contrib.auth.models import User, AbstractUser, Group, Permission
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from cities_light.models import City

from user.models import CustomUser


class Agency(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, unique=True)
    address = models.CharField(max_length=200)
    city = models.ForeignKey(City, null=True, on_delete=models.PROTECT)

    def __str__(self):
        return self.name + ' ' + self.city.name


class CarBrand(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class CarModel(models.Model):
    name = models.CharField(max_length=150, unique=True)
    car_model_price = models.FloatField()
    car_brand = models.ForeignKey(CarBrand, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Car(models.Model):
    GEARBOXES = (
        ('AT', 'Automatic'),
        ('MT', 'Manual'),
    )

    FUELS = (
        ('G', 'Gasoline'),
        ('D', 'Diesel'),
        ('H', 'Hybrid'),
        ('E', 'Electric'),
    )
    registration_number = models.CharField(max_length=20, unique=True)
    is_active = models.BooleanField(default=True)
    year = models.IntegerField()
    doors = models.PositiveSmallIntegerField()
    seats = models.PositiveSmallIntegerField()
    ac = models.BooleanField()
    gearbox = models.CharField(max_length=2, choices=GEARBOXES)
    fuel = models.CharField(max_length=1, choices=FUELS)
    picture = models.ImageField(upload_to='cars/', default='cars/default.png')
    agency = models.ForeignKey(Agency, on_delete=models.PROTECT)
    car_model = models.ForeignKey(CarModel, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.car_model)


class Rental(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    client = models.ForeignKey(CustomUser, related_name='client', on_delete=models.PROTECT)
    start_date = models.DateField()
    end_date = models.DateField()
    rental_price = models.FloatField()
    created_at = models.DateTimeField(default=timezone.now)
    paid = models.BooleanField(default=False)
    confirmed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.client.username) + str(self.car.car_model)

    def calculate_cost(self):
        days = (self.end_date - self.start_date).days + 1
        return days * self.rental_price

    def clean(self):
        if self.end_date <= self.start_date:
            raise ValidationError('End date must be after start date.')

home/models.py
from django.db import models

# Create your models here.

home/views.py
from datetime import datetime

from _decimal import Decimal
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import render
from django.utils import timezone
from employee.models import Car, Rental
from user.views import get_custom_user_roles


# Create your views here.
def index(request):
    return render(request, 'home/index.html')


def available_cars(request):
    if request.method == 'POST':
        from_date = request.POST.get('from_date')
        to_date = request.POST.get('to_date')
        # Validate the dates
        today = datetime.today().strftime('%Y-%m-%d')
        if from_date < today:
            messages.error(request, 'From date cannot be earlier than today.')
            return redirect('home:cars')
        elif to_date < from_date:
            messages.error(request, 'To date cannot be earlier than from date.')
            return redirect('home:cars')

        available_cars = Car.objects.exclude(
            Q(rental__start_date__lte=to_date, rental__end_date__gte=from_date) &
            Q(rental__paid=True)
        )
        context = {'available_cars': available_cars}
        return render(request, 'home/available_cars.html', context)
    else:
        context = {}
        return render(request, 'home/available_cars.html', context)


@login_required
def rent_car(request, car_id):
    user = request.user
    if not user.is_authenticated:
        messages.error(request, 'Login first.')
        return redirect('user:login')
    user_roles = get_custom_user_roles(request.user.id)
    if user_roles['is_owner']:
        messages.error(request, "You are not authorized to access this page.")
        return redirect('employee:index')
    car = get_object_or_404(Car, id=car_id)

    if request.method == 'POST':
        from_date_str = request.POST.get('from_date')
        to_date_str = request.POST.get('to_date')
        from_date = datetime.strptime(from_date_str, '%Y-%m-%d').date()
        to_date = datetime.strptime(to_date_str, '%Y-%m-%d').date()

        # check if the rental dates are valid (i.e. not already rented)
        if Rental.objects.filter(car=car, start_date__lte=to_date, end_date__gte=from_date, paid=True).exists():
            messages.error(request, 'The car is not available for the selected dates.')
            return redirect('home:cars')

        rental_days = (to_date - from_date).days + 1
        car_model_price = car.car_model.car_model_price
        rental_price = float(car_model_price) * float(rental_days)
        rental = Rental.objects.create(
            car=car,
            client=request.user,
            start_date=from_date,
            end_date=to_date,
            rental_price=rental_price,  # calculate rental price
        )
        messages.success(request, 'Car rented successfully.')
        return redirect('home:client_rentals')

    context = {'car': car}
    return render(request, 'home/rent_car.html', context)


@login_required
def client_rentals(request):
    user = request.user
    if not user.is_authenticated:
        return redirect('user:login')
    user_roles = get_custom_user_roles(request.user.id)
    if user_roles['is_owner']:
        messages.error(request, "You are not authorized to access this page.")
        return redirect('employee:index')
    rentals = Rental.objects.filter(client=request.user)
    context = {'rentals': rentals}
    return render(request, 'home/client_rentals.html', context)


def car_details(request, car_id):
    car = get_object_or_404(Car, id=car_id)
    context = {'car': car}
    return render(request, 'home/car_details.html', context)

home/templates/home/available_cars.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Rent Car{% endblock %}
{% block content %}
    <form method="POST" class="form-inline mt-4 mb-4" autocomplete="off">
        {% csrf_token %}
        <div class="form-group mx-sm-3 mb-2">
            <label for="from_date" class="sr-only">From Date:</label>
            <input type="date" name="from_date" class="form-control" placeholder="From Date" required>
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <label for="to_date" class="sr-only">To Date:</label>
            <input type="date" name="to_date" class="form-control" placeholder="To Date" required>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Search</button>
        <button type="reset" class="btn btn-secondary mb-2 ml-2">Reset</button>
    </form>
    {% if available_cars %}
        <div class="row">
            {% for car in available_cars %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <img class="card-img-top" src="{{ car.picture.url }}" width="400px" height="400px"
                             alt="Car Picture">
                        <div class="card-body">
                            <h5 class="card-title">{{ car.car_model }}</h5>
                            <p class="card-text">{{ car.year }} | {{ car.doors }} Doors | {{ car.seats }} Seats |
                                AC: {{ car.ac|yesno:"Yes,No" }}</p>
                            <p class="card-text">{{ car.get_gearbox_display }} | {{ car.get_fuel_display }}</p>


                            {% if user.is_authenticated %}
                                <form method="POST" action="{% url 'home:rent_car' car.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="from_date" value="{{ request.POST.from_date }}">
                                <input type="hidden" name="to_date" value="{{ request.POST.to_date }}">
                                <button class="btn btn-danger " type="submit">Rent me :)</button>
                            {% else %}
                                <a class="btn btn-danger" href="{% url 'user:login' %}" role="button">Login first</a>
                            {% endif %}
                            <h5 class="card-title animate__animated animate__bounceIn text-danger">{{ car.car_model.car_model_price|floatformat:2 }}
                                MAD</h5>
                            </form>


                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="col-md-12">
                    <p>No available cars found.</p>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

home/templates/home/car_details.html
{% extends 'base/base.html' %}
{% block title %}car{% endblock %}
{% block content %}
  <div class="container-fluid">
    <div class="row mt-4">
      <div class="col-md-8 offset-md-2">
        <div class="card">
          <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
              <h1 class="mb-0">{{ car.registration_number }}</h1>
              <a href="{% url 'home:client_rentals' %}" class="btn btn-secondary">Back to Rentals</a>
            </div>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-6">
                <img src="{{ car.picture.url }}" alt="{{ car.registration_number }}" class="img-fluid rounded mb-3">
                <h3>Car Details</h3>
                <ul class="list-group">
                  <li class="list-group-item"><strong>Model:</strong> {{ car.car_model }}</li>
                  <li class="list-group-item"><strong>Year:</strong> {{ car.year }}</li>
                  <li class="list-group-item"><strong>Doors:</strong> {{ car.doors }}</li>
                  <li class="list-group-item"><strong>Seats:</strong> {{ car.seats }}</li>
                  <li class="list-group-item"><strong>AC:</strong> {{ car.ac|yesno:"Yes,No" }}</li>
                  <li class="list-group-item"><strong>Gearbox:</strong> {{ car.get_gearbox_display }}</li>
                  <li class="list-group-item"><strong>Fuel:</strong> {{ car.get_fuel_display }}</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

home/templates/home/client_rentals.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Rents{% endblock %}
{% block content %}
    <h1>My Rentals</h1>
    {% if rentals %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Car</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Total Cost</th>
                <th>Paid</th>
                <th>Confirmed</th>
                <th>Actions </th>
            </tr>
            </thead>
            <tbody>
            {% for rental in rentals %}
                <tr>
                    <td>{{ rental.car.car_model }}</td>
                    <td>{{ rental.start_date }}</td>
                    <td>{{ rental.end_date }}</td>
                    <td>{{ rental.rental_price }}</td>
                    <td>
                        <input type="checkbox" name="paid" class="paid-checkbox" disabled
                               data-rental-id="{{ rental.id }}" {% if rental.paid %}checked{% endif %}
                        >
                    </td>
                    <td>

                        <input type="checkbox" name="confirmed" class="confirmed-checkbox" disabled
                               data-rental-id="{{ rental.id }}" {% if rental.confirmed %}checked{% endif %}
                        >
                    </td>
                    <td>
                        <a href="{% url 'home:car_details' rental.car.id %}">
                            <img src="{% static 'home/icons/iteration.png' %}" >
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No rentals found.</p>
    {% endif %}

{% endblock %}

home/templates/home/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>
    <style>
        #carouselExampleInterval .carousel-item img {
            max-height: 900px;
            margin: auto;
        }

        #carouselExampleInterval .carousel-caption {
            position: absolute;

            transform: translateY(-50%);
            width: 100%;
            text-align: center;
            z-index: 10;
        }

        #carouselExampleInterval .carousel-caption h5 {
            font-size: 3rem;
            font-weight: bold;
        }

        #carouselExampleInterval .carousel-caption p {
            font-size: 1.5rem;
            margin-top: 1rem;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="flex-container">
        <div id="carouselExampleInterval" class="carousel slide" Fdata-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active" data-bs-interval="4000">
                    <div class="carousel-caption d-inline  d-md-block">
                        <h5>Free cancellations on most booking </h5>
                        <p>Connecting you to the biggest brands in car rental.</p>
                    </div>
                    <img src="{% static 'home/images/4.jpg' %}" height="520px" class="d-block w-100" alt="...">

                </div>
                <div class="carousel-item" data-bs-interval="4000">
                    <img src="{% static 'home/images/5.jpg' %}" height="520px" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>60,000+ locations </h5>
                        <p>Clean cars. Flexible bookings. Socially distant rental counters..</p>
                    </div>
                </div>
                <div class="carousel-item" data-bs-interval="4000">
                    <img src="{% static 'home/images/car3.jpg' %}" height="520px" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Found the same deal for less?</h5>
                        <p>We’ll match the price.</p>
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval"
                    data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval"
                    data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
{% endblock %}