carRentalWeb/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/', include('employee.urls')),
    path('user/', include('user.urls')),
    path('', include('home.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, re_path
from . import views

app_name = 'home'

urlpatterns = [
    path("", views.index, name="index"),
    path("cars/", views.available_cars, name="cars"),
    path("client_rentals/", views.client_rentals, name='client_rentals'),
    path("car_details/<int:car_id>/", views.car_details, name='car_details'),
    path('rent_car/<int:car_id>/', views.rent_car, name='rent_car'),

]

user/urls.py
from django.urls import path
from .views import update_view, login_view, logout_view, register_view

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name="register"),
    path('profil/', update_view, name="profil"),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <title>{% block title %}CarRentalWeb{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>
    <style>
        html, body {
            height: 100%;
        }

        body > footer {
            position: sticky;
            top: 100vh;
        }
    </style>
</head>
<body class="vh-100">
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand text-decoration-none" href="{% url 'home:index' %}">
            <span class="fw-bold fs-4 align-middle">CRW</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active text-decoration-none" href="{% url 'home:cars' %}">
                        Rent Car
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active text-decoration-none" href="{% url 'home:client_rentals' %}">
                            My Rents
                        </a>
                    </li>
                {% endif %}
            </ul>
            <div>
                {% if user.is_authenticated %}
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active text-decoration-none" href={% url 'user:profil' %}>
                                My Account
                            </a>
                        </li>
                        <li class="nav-item">
                            <form method="post" action="{% url 'user:logout' %}" class="d-inline">
                                {% csrf_token %}
                                <input type="submit" value="Logout"
                                       class="btn btn-outline-light ">
                            </form>
                        </li>
                    </ul>

                {% else %}
                    <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    {% comment %}
                            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <button class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown"
                                                aria-expanded="false">
                                            Register
                                        </button>
                                        <ul class="dropdown-menu dropdown-menu-dark">
                                            <li><a class="dropdown-item" href="{% url 'user:register' %}">as
                                                Client</a></li>
                                            <li><a class="dropdown-item" href="#">as Owner</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                          {% endcomment %}
                    <ul class="navbar-nav">
                        <a class="btn btn-dark rounded-pill px-4 text-decoration-none"
                           href="{% url 'user:register' %}">
                            Register
                        </a>
                        <a class="btn btn-dark rounded-pill px-4 text-decoration-none"
                           href="{% url 'user:login' %}">
                            Login
                        </a>
                    </ul>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/notiflix@3.2.5/dist/notiflix-aio-3.2.5.min.js"
        integrity="sha256-LQj8h+SKqntnw8M/FP7QM+3dTqgHvB1JzZMVPD868Rg=" crossorigin="anonymous"></script>
{% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <script>
            Notiflix.Notify.success('{{ message }}', {
                position: 'center-top',
                fontSize: '17px',
                cssAnimationStyle: 'from-top',
            });
        </script>
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <script>
            Notiflix.Notify.failure('{{ message }}', {
                position: 'center-top',
                fontSize: '17px',
                cssAnimationStyle: 'from-top',
            });
        </script>
    {% endif %}
{% endfor %}
{% block js %}{% endblock %}
<!-- Create the sticky footer -->
<footer class="footer bg-dark">
    <div class="container text-center">
        <span class="text-light">Copyright © 2023 Crw.com by Badr&Khalid. All rights reserved</span>
    </div>
</footer>
</body>
</html>