carRentalWeb/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/', include('employee.urls')),
    path('user/', include('user.urls')),
    path('', include('home.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/urls.py
from django.urls import path

from . import views

app_name = 'employee'

urlpatterns = [
    path('', views.index, name='index'),
    # path('car/<int:car_id>/', views.car_detail, name='car_detail'),
    path('add-car/', views.add_car, name='add_car'),
    path('cars/', views.cars, name='cars'),
    path('update-car/<int:car_id>/', views.update_car, name='update_car'),
    path('delete-car/<int:car_id>/', views.delete_car, name='delete_car'),
    path('detail-car/<int:car_id>/', views.detail_car, name='detail_car'),
    path('update_rental/', views.update_rental, name='rentals'),
    path('rentals/', views.rentals, name='rentals'),
    path('rental-income/', views.rental_income, name='rental_income'),
    path('owner/profile/', views.owner_profile, name='owner_profile'),
    path('detail_client/<int:client_id>', views.detail_client, name='detail_client'),
    path('agency/', views.agency_view, name='agency'),

]

home/urls.py
from django.urls import path, re_path
from . import views

app_name = 'home'

urlpatterns = [
    path("", views.index, name="index"),
    path("cars/", views.available_cars, name="cars"),
    path("client_rentals/", views.client_rentals, name='client_rentals'),
    path("car_details/<int:car_id>/", views.car_details, name='car_details'),
    path('rent_car/<int:car_id>/', views.rent_car, name='rent_car'),

]

user/urls.py
from django.urls import path
from .views import update_view, login_view, logout_view, register_view

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name="register"),
    path('profil/', update_view, name="profil"),
]

employee/models.py
from django.contrib.auth.models import User, AbstractUser, Group, Permission
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from cities_light.models import City

from user.models import CustomUser


class Agency(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, unique=True)
    address = models.CharField(max_length=200)
    city = models.ForeignKey(City, null=True, on_delete=models.PROTECT)

    def __str__(self):
        return self.name + ' ' + self.city.name


class CarBrand(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class CarModel(models.Model):
    name = models.CharField(max_length=150, unique=True)
    car_model_price = models.FloatField()
    car_brand = models.ForeignKey(CarBrand, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Car(models.Model):
    GEARBOXES = (
        ('AT', 'Automatic'),
        ('MT', 'Manual'),
    )

    FUELS = (
        ('G', 'Gasoline'),
        ('D', 'Diesel'),
        ('H', 'Hybrid'),
        ('E', 'Electric'),
    )
    registration_number = models.CharField(max_length=20, unique=True)
    is_active = models.BooleanField(default=True)
    year = models.IntegerField()
    doors = models.PositiveSmallIntegerField()
    seats = models.PositiveSmallIntegerField()
    ac = models.BooleanField()
    gearbox = models.CharField(max_length=2, choices=GEARBOXES)
    fuel = models.CharField(max_length=1, choices=FUELS)
    picture = models.ImageField(upload_to='cars/', default='cars/default.png')
    agency = models.ForeignKey(Agency, on_delete=models.PROTECT)
    car_model = models.ForeignKey(CarModel, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.car_model)


class Rental(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    client = models.ForeignKey(CustomUser, related_name='client', on_delete=models.PROTECT)
    start_date = models.DateField()
    end_date = models.DateField()
    rental_price = models.FloatField()
    created_at = models.DateTimeField(default=timezone.now)
    paid = models.BooleanField(default=False)
    confirmed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.client.username) + str(self.car.car_model)

    def calculate_cost(self):
        days = (self.end_date - self.start_date).days + 1
        return days * self.rental_price

    def clean(self):
        if self.end_date <= self.start_date:
            raise ValidationError('End date must be after start date.')

employee/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Car, CarModel, Agency


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = '__all__'
        exclude = ['agency', 'is_active']


class CarModelForm(forms.ModelForm):
    class Meta:
        model = CarModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['car_brand'].widget.attrs['class'] = 'form-select'


class AgencyForm(forms.ModelForm):
    class Meta:
        model = Agency
        fields = ['name', 'email', 'phone', 'address', 'city']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
        }

employee/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.views.decorators.http import require_POST
from user.models import CustomUser, Role, RoleEnum
from user.views import get_custom_user_roles
from .forms import CarForm, AgencyForm
from employee.models import Car
from django.db.models import Sum, Count
from django.shortcuts import render
from django.utils import timezone
from .models import Rental


def index(request):
    user = request.user
    if not user.is_authenticated:
        return redirect('user:login')
    user_roles = get_custom_user_roles(request.user.id)
    if user.is_superuser:
        return redirect('/admin/')
    if not user_roles['is_owner']:
        return redirect('home:index')
    agency = user.agency
    cars = Car.objects.filter(agency=agency)
    users = CustomUser.objects. \
        exclude(is_superuser=True). \
        exclude(is_staff=True). \
        exclude(roles__in=Role.objects.filter(
        name__in=(
            RoleEnum.OWNER.value,
        )
    )
    )
    context = {
        'cars': cars,
        'is_owner': user_roles['is_owner'],
    }
    return render(request, 'employee/index.html', context)


def add_car(request):
    if request.user.agency is None:
        # Redirect to a different view, or display an error message
        messages.error(request, "You need to register your agency first.")
        return redirect('employee:agency')
    user = request.user
    if not user.is_authenticated:
        return redirect('user:login')
    user_roles = get_custom_user_roles(request.user.id)
    if user.is_superuser:
        return redirect('/admin/')
    if not user_roles['is_owner']:
        return redirect('home:index')
    form = CarForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        car = form.save(commit=False)
        car.agency = request.user.agency
        car.save()
        messages.success(request, "Car added successfully!")
        return redirect('employee:cars')
    return render(request, 'employee/add_car.html', {'form': form})


def cars(request):
    if request.user.agency is None:
        # Redirect to a different view, or display an error message
        messages.error(request, "You need to register your agency first.")
        return redirect('employee:agency')
    user = request.user
    if not user.is_authenticated:
        return redirect('user:login')
    user_roles = get_custom_user_roles(request.user.id)
    if user.is_superuser:
        return redirect('/admin/')
    if not user_roles['is_owner']:
        return redirect('home:index')

    cars = Car.objects.filter(agency=user.agency)

    context = {
        'cars': cars,
    }
    return render(request, 'employee/cars.html', context)


@login_required
def rental_income(request, car_id):
    if request.user.agency is None:
        # Redirect to a different view, or display an error message
        messages.error(request, "You need to register your agency first.")
        return redirect('employee:agency')
    car = get_object_or_404(Car, id=car_id)
    rental_income = Rental.objects.filter(car=car, paid=True).aggregate(Sum('rental_price'))
    total_income = rental_income['rental_price__sum'] or 0
    context = {'car': car, 'total_income': total_income}
    return render(request, 'employee/rental_income.html', context)


def update_car(request, car_id):
    if request.user.agency is None:
        # Redirect to a different view, or display an error message
        messages.error(request, "You need to register your agency first.")
        return redirect('employee:agency')
    car = get_object_or_404(Car, id=car_id)
    if request.method == 'POST':
        form = CarForm(request.POST, request.FILES, instance=car)
        if form.is_valid():
            form.save()
            messages.success(request, "Car has been updated successfully.")
            return redirect('employee:cars')
    else:
        form = CarForm(instance=car)
    context = {
        'form': form,
        'car': car,
    }
    return render(request, 'employee/update_car.html', context)


def delete_car(request, car_id):
    if request.user.agency is None:
        # Redirect to a different view, or display an error message
        messages.error(request, "You need to register your agency first.")
        return redirect('employee:agency')
    car = get_object_or_404(Car, id=car_id)
    if request.method == 'POST':
        car.delete()
        messages.add_message(request, messages.INFO, 'Car has been deleted.')
        return redirect('employee:cars')
    context = {
        'car': car,
    }
    return render(request, 'employee/delete_car.html', context)


def detail_car(request, car_id):
    if request.user.agency is None:
        # Redirect to a different view, or display an error message
        messages.error(request, "You need to register your agency first.")
        return redirect('employee:agency')
    car = get_object_or_404(Car, id=car_id)
    context = {'car': car}
    return render(request, 'employee/detail_car.html', context)


@login_required
def rentals(request):
    if request.user.agency is None:
        # Redirect to a different view, or display an error message
        messages.error(request, "You need to register your agency first.")
        return redirect('employee:agency')
    user = request.user
    if not user.is_authenticated:
        return redirect('user:login')
    user_roles = get_custom_user_roles(request.user.id)
    if not user_roles['is_owner']:
        messages.error(request, "You are not authorized to access this page.")
        return redirect('home:index')

    agency = user.agency
    cars = Car.objects.filter(agency=agency)
    rentals = Rental.objects.filter(car__in=cars)

    context = {
        'cars': cars,
        'rentals': rentals,
        'is_owner': user_roles['is_owner'],
    }
    return render(request, 'employee/rentals.html', context)


@require_POST
def update_rental(request):
    if request.user.agency is None:
        # Redirect to a different view, or display an error message
        messages.error(request, "You need to register your agency first.")
        return redirect('employee:agency')
    rental_id = request.POST.get('rental_id')
    is_paid = request.POST.get('is_paid') == 'true'
    is_confirmed = request.POST.get('is_confirmed') == 'true'

    rental = Rental.objects.get(id=rental_id)
    rental.paid = is_paid
    rental.confirmed = is_confirmed
    rental.save()

    return JsonResponse({'success': 'Rental updated successfully'})


@login_required
def rental_income(request):
    if request.user.agency is None:
        # Redirect to a different view, or display an error message
        messages.error(request, "You need to register your agency first.")
        return redirect('employee:agency')
    agency = request.user.agency
    rentals = Rental.objects.filter(car__agency=agency, paid=True)

    total_income = rentals.aggregate(total_income=Sum('rental_price'))['total_income'] or 0

    start_date = rentals.order_by('start_date').first().start_date if rentals.exists() else timezone.now().date()
    end_date = rentals.order_by('-end_date').first().end_date if rentals.exists() else timezone.now().date()

    months_diff = (end_date.year - start_date.year) * 12 + (end_date.month - start_date.month) + 1
    per_month_income = total_income / months_diff if months_diff > 0 else 0

    top_rented_car = rentals.values('car__car_model__name', 'car__car_model__car_brand__name') \
        .annotate(total_rentals=Count('id')) \
        .order_by('-total_rentals') \
        .first()
    topcar_profit = rentals.values('car__car_model__name',
                                   'car__car_model__car_brand__name').annotate(
        total_rental_price=Sum('rental_price')).order_by('-total_rental_price').first()
    context = {
        'total_income': total_income,
        'per_month_income': per_month_income,
        'top_rented_car': top_rented_car,
        'topcar_profit': topcar_profit,
    }

    return render(request, 'employee/rental_income.html', context)


@login_required
def owner_profile(request):
    agency = request.user.agency
    context = {
        'user': request.user,
        'agency': agency,
    }
    return render(request, 'employee/owner_profile.html', context)


@login_required
def detail_client(request, client_id):
    if request.user.agency is None:
        # Redirect to a different view, or display an error message
        messages.error(request, "You need to register your agency first.")
        return redirect('employee:agency')
    user = request.user
    if not user.is_authenticated:
        return redirect('user:login')
    user_roles = get_custom_user_roles(request.user.id)
    if not user_roles['is_owner']:
        messages.error(request, "You are not authorized to access this page.")
        return redirect('home:index')
    client = get_object_or_404(CustomUser, id=client_id)
    context = {'client': client}
    return render(request, 'employee/detail_client.html', context)


def agency_view(request):
    if request.user.agency is not None:
        # Redirect to a different view, or display an error message
        return redirect('employee:owner_profile')
    if request.method == 'POST':
        form = AgencyForm(request.POST)
        if form.is_valid():
            agency = form.save()
            # Link the agency to the current user's agency field
            request.user.agency = agency
            request.user.save()
            # Redirect to a success page
            return redirect('employee:owner_profile')
    else:
        form = AgencyForm()
    return render(request, 'employee/agency.html', {'form': form})

employee/templates/employee/agency.html
{% extends 'employee/base.html' %}

{% block content %}
    <h2 class="text-center mt-3">Register Agency</h2>
    <form method="POST"
          class="col-xxl-3 col-xl-4 col-lg-5 col-md-6 col-11 mx-auto my-4 p-4 border rounded shadow needs-validation">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
{% endblock %}

employee/templates/employee/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="">

    <title>{% block title %}CarRentalWeb{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>
    <style>
        html, body {
            height: 100%;
        }

        body > footer {
            position: sticky;
            top: 100vh;
        }
    </style>
</head>
<body class="vh-100">
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand text-decoration-none" href="{% url 'employee:index' %}">
            <span class="fw-bold fs-4 align-middle">CRW</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active text-decoration-none" id="nav_rent" href="{% url 'employee:rentals' %}">
                        Reservations
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active text-decoration-none" href="{% url 'employee:cars' %}">
                        My Cars
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active text-decoration-none" href="{% url 'employee:rental_income' %}">
                        Statistics
                    </a>
                </li>
            </ul>
            <div>
                {% if user.is_authenticated %}
                    <a class="btn btn-outline-light border border-light border-2 rounded-pill px-4 text-decoration-none"
                       href="{% url 'employee:owner_profile' %}">
                        My Account
                    </a>
                    <form method="post" action="{% url 'user:logout' %}" class="d-inline">
                        {% csrf_token %}
                        <input type="submit" value="Logout"
                               class="btn btn-outline-light border border-light border-2 rounded-pill px-3">
                    </form>
                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active text-decoration-none" href="#" id="navbarDropdown"
                           role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Register
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'user:clientregister' %}">Register as Client</a>
                            </li>
                            <li><a class="dropdown-item" href="#">Register as Owner</a></li>
                        </ul>
                    </li>
                    <a class="btn btn-light rounded-pill px-4 text-decoration-none"
                       href="{% url 'user:login' %}">
                        Login
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/notiflix@3.2.5/dist/notiflix-aio-3.2.5.min.js"
        integrity="sha256-LQj8h+SKqntnw8M/FP7QM+3dTqgHvB1JzZMVPD868Rg=" crossorigin="anonymous"></script>
{% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <script>
            Notiflix.Notify.success('{{ message }}', {
                position: 'center-top',
                fontSize: '17px',
                cssAnimationStyle: 'from-top',
            });
        </script>
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <script>
            Notiflix.Notify.failure('{{ message }}', {
                position: 'center-top',
                fontSize: '17px',
                cssAnimationStyle: 'from-top',
            });
        </script>
    {% endif %}
{% endfor %}
{% block js %}{% endblock %}
<footer class="footer bg-dark">
    <div class="container text-center">
        <span class="text-light">Copyright © 2023 Crw.com by Badr&Khalid. All rights reserved</span>
    </div>
</footer>
</body>
</html>

employee/templates/employee/cars.html
{% extends 'employee/base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row mt-4">
            <div class="col-md-8 offset-md-2">
                <h1 class="text-center mb-4">Cars</h1>
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Registration Number</th>
                        <th>Model</th>
                        <th>Year</th>
                        <th>Doors</th>
                        <th>Seats</th>
                        <th>AC</th>
                        <th>Gearbox</th>
                        <th>Fuel</th>
                        <th>Picture</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for car in cars %}
                        <tr>
                            <td>{{ car.registration_number }}</td>
                            <td>{{ car.car_model }}</td>
                            <td>{{ car.year }}</td>
                            <td>{{ car.doors }}</td>
                            <td>{{ car.seats }}</td>
                            <td>{{ car.ac|yesno:"Yes,No" }}</td>
                            <td>{{ car.get_gearbox_display }}</td>
                            <td>{{ car.get_fuel_display }}</td>
                            <td><img src="{{ car.picture.url }}" alt="Car Picture" width="100" height="100"></td>
                            <td>
                                <a href="{% url 'employee:detail_car' car.id %}" class="btn btn-sm btn-primary">View</a>
                                <a href="{% url 'employee:update_car' car.id %}" class="btn btn-sm btn-success">Edit</a>
                                <a href="{% url 'employee:delete_car' car.id %}"
                                   class="btn btn-sm btn-danger">Delete</a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="10">No cars available.</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'employee:add_car' %}" class="btn btn-primary">Add Car</a>
            </div>
        </div>
    </div>
{% endblock %}

employee/templates/employee/delete_car.html
{% extends 'employee/base.html' %}

{% block content %}
  <div class="container-fluid">
    <div class="row mt-4">
      <div class="col-md-8 offset-md-2">
        <h1 class="text-center mb-4">Delete Car</h1>
        <form method="post">
          {% csrf_token %}
          <p>Are you sure you want to delete this car?</p>
          <button type="submit" class="btn btn-danger">Delete</button>
          <a href="{% url 'employee:cars' %}" class="btn btn-secondary">Cancel</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

employee/templates/employee/detail_car.html
{% extends 'employee/base.html' %}

{% block content %}
  <div class="container-fluid">
    <div class="row mt-4">
      <div class="col-md-8 offset-md-2">
        <div class="card">
          <div class="card-header">
            <h1 class="text-center mb-0">{{ car.registration_number }}</h1>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-6">
                <img src="{{ car.picture.url }}" alt="{{ car.registration_number }}" class="img-fluid rounded mb-3">
                <h3>Car Details</h3>
                <ul class="list-group">
                  <li class="list-group-item"><strong>Model:</strong> {{ car.car_model }}</li>
                  <li class="list-group-item"><strong>Year:</strong> {{ car.year }}</li>
                  <li class="list-group-item"><strong>Doors:</strong> {{ car.doors }}</li>
                  <li class="list-group-item"><strong>Seats:</strong> {{ car.seats }}</li>
                  <li class="list-group-item"><strong>AC:</strong> {{ car.ac|yesno:"Yes,No" }}</li>
                  <li class="list-group-item"><strong>Gearbox:</strong> {{ car.get_gearbox_display }}</li>
                  <li class="list-group-item"><strong>Fuel:</strong> {{ car.get_fuel_display }}</li>
                </ul>
              </div>
              <div class="col-md-6">
                <h3>Actions</h3>
                <a href="{% url 'employee:update_car' car.id %}" class="btn btn-primary mb-2">Edit</a>
               <a href="{% url 'employee:delete_car' car.id %}" class="btn btn-danger mb-2">Delete</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Delete Car Modal -->
  <div class="modal fade" id="deleteCarModal" tabindex="-1" role="dialog" aria-labelledby="deleteCarModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteCarModalLabel">Confirm Delete</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this car?
        </div>
        <div class="modal-footer">
          <form action="{% url 'employee:delete_car' car.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

employee/templates/employee/index.html
{% extends 'employee/base.html' %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Owner Dashboard</div>

                    <div class="card-body">
                        <p>Welcome {{ user.first_name }} {{ user.last_name }}!</p>
                        <p>Here you can manage your Cars and view your rental income.</p>
                        {% if  not user.agency %}
                            <p>But first, you need to <a href="{% url 'employee:agency' %}">register your agency</a>.
                            </p>
                        {% endif %}
                        <div class="row">
                            <div class="col-md-6">
                                <a href="{% url 'employee:add_car' %}" class="btn btn-primary">Add Car</a>
                            </div>
                            <div class="col-md-6">
                                <a href="{% url 'employee:cars' %}" class="btn btn-secondary">View Cars</a>
                            </div>

                        </div>
                        <div class="row mt-3">
                            <div class="col-md-6">
                                <a href="{% url 'employee:rental_income' %}" class="btn btn-primary">View Rental
                                    Income</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

employee/templates/employee/update_car.html
{% extends 'employee/base.html' %}

{% block content %}
  <div class="container my-4">
    <div class="row justify-content-center">
      <div class="col-md-8">
         <h1 class="text-center mb-4">Update Car</h1>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_registration_number">Registration Number:</label>
            {{ form.registration_number }}
          </div>
          <div class="form-group">
            <label for="id_car_model">Model:</label>
            {{ form.car_model}}
          </div>
          <div class="form-group">
            <label for="id_year">Year:</label>
            {{ form.year }}
          </div>
          <div class="form-group">
            <label for="id_doors">Doors:</label>
            {{ form.doors }}
          </div>
          <div class="form-group">
            <label for="id_seats">Seats:</label>
            {{ form.seats }}
          </div>
          <div class="form-group form-check">
            <label class="form-check-label">
              {{ form.ac}} AC
            </label>
          </div>
          <div class="form-group">
            <label for="id_gearbox">Gearbox:</label>
            {{ form.gearbox }}
          </div>
          <div class="form-group">
            <label for="id_fuel">Fuel:</label>
            {{ form.fuel }}
          </div>
          <div class="form-group">
            <label for="id_picture">Picture:</label>
            {{ form.picture }}
          </div>
          <button type="submit" class="btn btn-primary">Update Car</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}